### ISSUE TITLE
famli filter raises an IndexError: list index out of range

### ISSUE THREAD

**Issue by adriaaula** [FredHutch/FAMLI#17]
Hello there, 

With a tabulat output blastx style, FAMLI raises the following error: 

Run (python 2.7)
`famli filter --input ~/scratch/biogem_7years_bigoutputs/mapping_diamond/BL090113.aln --output-aln ~/scratch/here --logfile ~/scratch/log.here --batchsize 100`

output 
```
2019-10-07 18:17:56,556 INFO     [FAMLI parse] Reading in batches of 100 alignments
2019-10-07 18:17:56,557 INFO     [FAMLI parse] Reading in alignments
Traceback (most recent call last):
  File "/home/aauladell/.local/bin/famli", line 11, in <module>
    sys.exit(main())
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/run_famli.py", line 413, in main
    FAMLI()
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/run_famli.py", line 46, in __init__
    self.filter()
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/run_famli.py", line 389, in filter
    batchsize=args.batchsize,
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/famli_helpers.py", line 442, in parse_alignment
    SLEN_i=SLEN_i
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/famli_helpers.py", line 127, in yield_alignments
    SLEN_i=SLEN_i
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/famli_helpers.py", line 48, in parse
    self.subject_len[subject] = int(line_list[SLEN_i])
IndexError: list index out of range
```
Type of data (Blast-like, from outfmt 6)
```
A00500:44:HFHKYDSXX:1:1101:12861:1094	BL101214.k127_1891491.mgm_2186797	87.8	49	6	0	3	149	136	184	4.2e-20	95.9
A00500:44:HFHKYDSXX:1:1101:12861:1094	BL091105.k127_798690.mgm_1044987	85.7	49	7	0	3	149	136	184	6.1e-19	92.0
A00500:44:HFHKYDSXX:1:1101:30454:1188	BL111219.k127_2883972_1.pro_1697223	100.0	48	0	0	145	2	203	250	3.3e-22	102.8
A00500:44:HFHKYDSXX:1:1101:30454:1188	BL130312.k127_34594.mgm_43896	100.0	48	0	0	145	2	328	375	3.3e-22	102.8
A00500:44:HFHKYDSXX:1:1101:30454:1188	BL141216.k127_2091761.mgm_2555336	87.5	48	6	0	145	2	328	375	1.2e-19	94.4
A00500:44:HFHKYDSXX:1:1101:30454:1188	BL090113.k127_1294355.mgm_1466399	87.5	48	6	0	145	2	328	375	1.5e-19	94.0
A00500:44:HFHKYDSXX:1:1101:30454:1188	BL140211.k127_1002249.mgm_1173703	87.5	48	6	0	145	2	75	122	1.5e-19	94.0
A00500:44:HFHKYDSXX:1:1101:30454:1188	BL090113.k127_1294355_1.pro_690026	87.5	48	6	0	145	2	187	234	1.5e-19	94.0
A00500:44:HFHKYDSXX:1:1101:30454:1188	BL120313.k127_3112132.mgm_3604898	87.5	48	6	0	145	2	32	79	2.0e-19	93.6
A00500:44:HFHKYDSXX:1:1101:30454:1188	BL140114.k127_3808333.mgm_4308952	87.5	48	6	0	145	2	328	375	2.0e-19	93.6
```

**Comment by sminot** [comment]
Two notes:

  * I'm not sure how Python interprets the `~` string -- can you replace that with $HOME and try again?
  * I'm not sure why you included `--batchsize 100` -- can you remove that flag and try again?

Thanks!

**Comment by adriaaula** [comment]
Yes, 

```
famli filter --input $HOME/scratch/biogem_7years_bigoutputs/mapping_diamond/BL131105.aln --output-aln $HOME/scratch/here --logfile $HOME/scratch/log.here
```
```
2019-10-10 11:56:07,960 INFO     [FAMLI parse] Batchsize feature disabled, reading all alignments
2019-10-10 11:56:07,961 INFO     [FAMLI parse] Reading in alignments
Traceback (most recent call last):
  File "/home/aauladell/.local/bin/famli", line 11, in <module>
    sys.exit(main())
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/run_famli.py", line 413, in main
    FAMLI()
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/run_famli.py", line 46, in __init__
    self.filter()
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/run_famli.py", line 389, in filter
    batchsize=args.batchsize,
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/famli_helpers.py", line 442, in parse_alignment
    SLEN_i=SLEN_i
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/famli_helpers.py", line 98, in yield_alignments
    SLEN_i=SLEN_i
  File "/home/aauladell/.local/lib/python2.7/site-packages/famli/famli_helpers.py", line 48, in parse
    self.subject_len[subject] = int(line_list[SLEN_i])
IndexError: list index out of range
```
Same error. It seems to be able to read it isn't it?  

I add an example output from blastx output coming from diamond: 

[example_blastx_output.txt](https://github.com/FredHutch/FAMLI/files/3711728/example_blastx_output.txt)


This was the code used for generating the `.aln` file: 

```
diamond blastx --query ~/scratch/samswhole/${SAMPLE}.fastq.gz \
               --out ${OUT_DIR}/${SAMPLE}.aln \
               --min-score 20 \
               --threads 24 --db ${DIAMONDDB} \
               --outfmt 6 --query-cover 95 \
               --id 80 --top 10 --block-size 9 \
               --query-gencode 11 --unal 0
```

**Comment by sminot** [comment]
Thanks for including the command you used to run DIAMOND. It's possible that this is because you used different options to run DIAMOND, and so the alignment file isn't formatted with all of the information needed. Try adding this flag to the DIAMOND call and trying it again:

```
--outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen
```

**Comment by adriaaula** [comment]
this worked like a charm! 

Thanks a lot @sminot
